packages: []

catalogs:
  build:
    '@nuxt/content': ^3.11.0
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.12.1
    '@nuxt/icon': ^2.2.1
    '@nuxt/schema': ^4.3.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.3
    '@tailwindcss/vite': ^4.1.18
    '@vite-pwa/nuxt': ^1.1.0
    '@vueuse/nuxt': ^14.1.0
    better-sqlite3: ^12.6.2
    nuxt: ^4.3.0
    tailwindcss: ^4.1.18
    unplugin: ^2.3.10
    vite: ^7.1.12
    zod: ^4.3.6
  common:
    '@bubblesortt/nuxt-es-toolkit': ^1.0.9
    alova: ^3.5.0
    dayjs-nuxt: ^2.1.11
  dev:
    '@nuxt/hints': 1.0.0-alpha.6
    '@th1o/frontend-lint': ^0.0.4
    '@types/node': ^25.0.10
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    stylelint: ^17.0.0
    typescript: ^5.9.3
    vue-tsc: ^3.2.2
  frontend:
    '@nuxt/image': ^2.0.0
    '@nuxt/ui': ^4.4.0
    '@nuxtjs/device': ^4.0.0
    '@vueuse/core': ^14.1.0
    pinia: ^3.0.4
    vue: ^3.5.27
  icon:
    '@iconify-json/lucide': ^1.2.87
    '@iconify-json/simple-icons': ^1.2.68

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sqlite3
  - unrs-resolver
  - vue-demi

peerDependencyRules:
  allowedVersions:
    '@typescript-eslint/experimental-utils>eslint': '*'
    '@typescript-eslint/utils>eslint': '*'

shellEmulator: true

trustPolicy: no-downgrade
